apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    protocol: TCP
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    app: client
  type: LoadBalancer