apiVersion: v1
kind: Service
metadata:
  #namespace: monitoring
  name: jaeger
  labels:
    app: jaeger
spec:
  selector:
    app: jaeger
  type: NodePort
  ports:
    - name: jaeger-agent-thrift
      protocol: UDP
      port: 6831
    - name: jaeger-query
      protocol: TCP
      port: 16686
    - name: jaeger-collector
      protocol: TCP
      port: 14268