apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo
        name: mongodb
        ports:
        - containerPort: 27017
        # volumeMounts:
        # - mountPath: C:/Users/sacjain1/Desktop/My Code/React Group Chat/server/data/db
        #   name: mongodata
      restartPolicy: Always
      # volumes:
      # - name: mongodata
      #   persistentVolumeClaim:
      #     claimName: mongodata
  selector:
    matchLabels:
      app: mongodb